### ISSUE TITLE
Rozčlenění Modelu

### ISSUE THREAD

**Issue by hajek-raven** [rawac/agenda#2]
Myslím že by bylo vhodné model více rozčlenit. V této chvíli většina konečných modelů (Users, Mebership, ...) dědí z `\App\Model\Common\GridTableModel` a to podle mě není správně.

Příklad u Users:
Vytvořit základní model uživatelů (`UserModel`) který bude využívat `\DibiFluent`. Zároveň vytvořit další model např.: `UserGridModel`, který bude přizpůsobený rozhraní `\Grido\DataSources\IDataSource` které Grido vyžaduje. Tím se velice usnadní rozšiřování těch částí applikace, které s Gridem vůbec nesouvisejí.

**Comment by rawac** [comment]
Vím. Jako společný předek měl sloužit TableModel. Jenže pak to znamenalo odvodit od každé "UserModel" třídy její dceru a v té implementovat \Grido\DataSources\IDataSource, což znamená do každé nakopírovat stejný kus kódu. Což je asi čistší řešení, bohužel je pracné a zdá se mi náročné na údržbu. Ideální by byla možnost dědit metody ze dvou tříd, tu ale nemáme.

Kouknu, jak moc pracné to bude.

**Comment by hajek-raven** [comment]
Pokusím se přepsat ten UserModel a uvidím jestli se to vyplatí nebo ne.
